// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAccountUserReference = `-- name: CreateAccountUserReference :exec
INSERT INTO accounts_users 
(
    account_id,
    user_id,
    created_at,
    updated_at
)
VALUES 
(
    $1,
    $2,
    NOW(),
    NOW()
)
`

type CreateAccountUserReferenceParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CreateAccountUserReference(ctx context.Context, arg CreateAccountUserReferenceParams) error {
	_, err := q.db.ExecContext(ctx, createAccountUserReference, arg.AccountID, arg.UserID)
	return err
}
