// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups 
(
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_id,
    account_id
)
VALUES 
(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_id AS parent_group
`

type CreateGroupParams struct {
	Description sql.NullString
	Name        string
	ParentID    uuid.NullUUID
	AccountID   uuid.UUID
}

type CreateGroupRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Name        string
	ParentGroup uuid.NullUUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.Description,
		arg.Name,
		arg.ParentID,
		arg.AccountID,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroup,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec

DELETE FROM groups
WHERE id = $1 AND account_id = $2
`

type DeleteGroupParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.ID, arg.AccountID)
	return err
}

const getGroup = `-- name: GetGroup :one

SELECT
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_id AS parent_group
FROM groups
WHERE id = $1 AND account_id = $2
`

type GetGroupParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetGroupRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Name        string
	ParentGroup uuid.NullUUID
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getGroup, arg.ID, arg.AccountID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroup,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many

SELECT
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_id AS parent_group
FROM groups
WHERE account_id = $1
AND
    (
        $2::timestamp IS NULL 
        OR $2::timestamp > created_at
    )
AND 
    (
        $3::timestamp IS NULL 
        OR $3::timestamp < created_at
    )
AND 
    (
        $4::timestamp IS NULL 
        OR $4::timestamp >= created_at
    )
AND 
    (
        $5::timestamp IS NULL 
        OR $5::timestamp <= created_at
    )
AND 
    (
        $6::timestamp IS NULL 
        OR $6::timestamp > updated_at
    )
AND 
    (
        $7::timestamp IS NULL 
        OR $7::timestamp < updated_at
    )
AND 
    (
        $8::timestamp IS NULL 
        OR $8::timestamp >= updated_at
    )
AND 
    (
        $9::timestamp IS NULL 
        OR $9::timestamp <= updated_at
    )
AND 
    (
        $10::uuid IS NULL
        OR $10::uuid > id
    )
AND 
    (
        $11::uuid IS NULL
        OR $11::uuid < id
    )
AND 
    (
        $12::uuid IS NULL 
        OR parent_id = $12::uuid
    )
AND 
    (
        $13::text IS NULL 
        OR description LIKE $13::text
    )
AND 
    (
        $14::text IS NULL 
        OR name LIKE $14::text
    )
ORDER BY created_at DESC
LIMIT COALESCE($15::int, 10)
`

type ListGroupsParams struct {
	AccountID     uuid.UUID
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtLt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	ParentID      uuid.NullUUID
	Description   sql.NullString
	Name          sql.NullString
	Limit         sql.NullInt32
}

type ListGroupsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Name        string
	ParentGroup uuid.NullUUID
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.ParentID,
		arg.Description,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Name,
			&i.ParentGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one

UPDATE groups
SET
    updated_at = NOW(),
    description = COALESCE($1, description),
    name = COALESCE($2, name),
    parent_id = COALESCE($3, parent_id)
WHERE id = $4 AND account_id = $5
RETURNING
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_id AS parent_group
`

type UpdateGroupParams struct {
	Description sql.NullString
	Name        sql.NullString
	ParentID    uuid.NullUUID
	ID          uuid.UUID
	AccountID   uuid.UUID
}

type UpdateGroupRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Name        string
	ParentGroup uuid.NullUUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Description,
		arg.Name,
		arg.ParentID,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroup,
	)
	return i, err
}
