// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventories.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories 
(
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    account_id,
    item_id
)
VALUES 
(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    item_id AS item
`

type CreateInventoryParams struct {
	InStock   int32
	Orderable sql.NullInt32
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type CreateInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Item      uuid.UUID
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (CreateInventoryRow, error) {
	row := q.db.QueryRowContext(ctx, createInventory,
		arg.InStock,
		arg.Orderable,
		arg.AccountID,
		arg.ItemID,
	)
	var i CreateInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Item,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec

DELETE FROM inventories
WHERE id = $1 AND account_id = $2
`

type DeleteInventoryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteInventory(ctx context.Context, arg DeleteInventoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteInventory, arg.ID, arg.AccountID)
	return err
}

const getInventory = `-- name: GetInventory :one

SELECT
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    item_id AS item
FROM inventories
WHERE id = $1 AND account_id = $2
`

type GetInventoryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Item      uuid.UUID
}

func (q *Queries) GetInventory(ctx context.Context, arg GetInventoryParams) (GetInventoryRow, error) {
	row := q.db.QueryRowContext(ctx, getInventory, arg.ID, arg.AccountID)
	var i GetInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Item,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many

SELECT
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    item_id AS item
FROM inventories
WHERE account_id = $1
AND
    (
        $2::timestamp IS NULL 
        OR $2::timestamp > created_at
    )
AND 
    (
        $3::timestamp IS NULL 
        OR $3::timestamp < created_at
    )
AND 
    (
        $4::timestamp IS NULL 
        OR $4::timestamp >= created_at
    )
AND 
    (
        $5::timestamp IS NULL 
        OR $5::timestamp <= created_at
    )
AND 
    (
        $6::timestamp IS NULL 
        OR $6::timestamp > updated_at
    )
AND 
    (
        $7::timestamp IS NULL 
        OR $7::timestamp < updated_at
    )
AND 
    (
        $8::timestamp IS NULL 
        OR $8::timestamp >= updated_at
    )
AND 
    (
        $9::timestamp IS NULL 
        OR $9::timestamp <= updated_at
    )
AND 
    (
        $10::uuid IS NULL
        OR $10::uuid > id
    )
AND 
    (
        $11::uuid IS NULL
        OR $11::uuid < id
    )
ORDER BY created_at DESC
LIMIT COALESCE($12::int, 10)
`

type ListInventoriesParams struct {
	AccountID     uuid.UUID
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtLt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	Limit         sql.NullInt32
}

type ListInventoriesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Item      uuid.UUID
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]ListInventoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventories,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoriesRow
	for rows.Next() {
		var i ListInventoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InStock,
			&i.Orderable,
			&i.Item,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one

UPDATE inventories
SET
    updated_at = NOW(),
    in_stock = COALESCE($1, in_stock),
    orderable = COALESCE($2, orderable)
WHERE id = $3 AND account_id = $4
RETURNING
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    item_id AS item
`

type UpdateInventoryParams struct {
	InStock   sql.NullInt32
	Orderable sql.NullInt32
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Item      uuid.UUID
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (UpdateInventoryRow, error) {
	row := q.db.QueryRowContext(ctx, updateInventory,
		arg.InStock,
		arg.Orderable,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Item,
	)
	return i, err
}
