// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_identifiers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItemIdentifier = `-- name: CreateItemIdentifier :one
INSERT INTO item_identifiers 
(
    id,
    created_at,
    updated_at,
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    account_id,
    item_id
)
VALUES 
(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, created_at, updated_at, ean, gtin, isbn, jan, mpn, nsn, upc, qr, account_id, item_id
`

type CreateItemIdentifierParams struct {
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

func (q *Queries) CreateItemIdentifier(ctx context.Context, arg CreateItemIdentifierParams) (ItemIdentifier, error) {
	row := q.db.QueryRowContext(ctx, createItemIdentifier,
		arg.Ean,
		arg.Gtin,
		arg.Isbn,
		arg.Jan,
		arg.Mpn,
		arg.Nsn,
		arg.Upc,
		arg.Qr,
		arg.AccountID,
		arg.ItemID,
	)
	var i ItemIdentifier
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ean,
		&i.Gtin,
		&i.Isbn,
		&i.Jan,
		&i.Mpn,
		&i.Nsn,
		&i.Upc,
		&i.Qr,
		&i.AccountID,
		&i.ItemID,
	)
	return i, err
}
