// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Countries string

const (
	CountriesAF Countries = "AF"
	CountriesAX Countries = "AX"
	CountriesAL Countries = "AL"
	CountriesDZ Countries = "DZ"
	CountriesAS Countries = "AS"
	CountriesAD Countries = "AD"
	CountriesAO Countries = "AO"
	CountriesAI Countries = "AI"
	CountriesAQ Countries = "AQ"
	CountriesAG Countries = "AG"
	CountriesAR Countries = "AR"
	CountriesAM Countries = "AM"
	CountriesAW Countries = "AW"
	CountriesAU Countries = "AU"
	CountriesAT Countries = "AT"
	CountriesAZ Countries = "AZ"
	CountriesBS Countries = "BS"
	CountriesBH Countries = "BH"
	CountriesBD Countries = "BD"
	CountriesBB Countries = "BB"
	CountriesBY Countries = "BY"
	CountriesBE Countries = "BE"
	CountriesBZ Countries = "BZ"
	CountriesBJ Countries = "BJ"
	CountriesBM Countries = "BM"
	CountriesBT Countries = "BT"
	CountriesBO Countries = "BO"
	CountriesBQ Countries = "BQ"
	CountriesBA Countries = "BA"
	CountriesBW Countries = "BW"
	CountriesBV Countries = "BV"
	CountriesBR Countries = "BR"
	CountriesIO Countries = "IO"
	CountriesBN Countries = "BN"
	CountriesBG Countries = "BG"
	CountriesBF Countries = "BF"
	CountriesBI Countries = "BI"
	CountriesCV Countries = "CV"
	CountriesKH Countries = "KH"
	CountriesCM Countries = "CM"
	CountriesCA Countries = "CA"
	CountriesKY Countries = "KY"
	CountriesCF Countries = "CF"
	CountriesTD Countries = "TD"
	CountriesCL Countries = "CL"
	CountriesCN Countries = "CN"
	CountriesCX Countries = "CX"
	CountriesCC Countries = "CC"
	CountriesCO Countries = "CO"
	CountriesKM Countries = "KM"
	CountriesCD Countries = "CD"
	CountriesCG Countries = "CG"
	CountriesCK Countries = "CK"
	CountriesCR Countries = "CR"
	CountriesCI Countries = "CI"
	CountriesHR Countries = "HR"
	CountriesCU Countries = "CU"
	CountriesCW Countries = "CW"
	CountriesCY Countries = "CY"
	CountriesCZ Countries = "CZ"
	CountriesDK Countries = "DK"
	CountriesDJ Countries = "DJ"
	CountriesDM Countries = "DM"
	CountriesDO Countries = "DO"
	CountriesEC Countries = "EC"
	CountriesEG Countries = "EG"
	CountriesSV Countries = "SV"
	CountriesGQ Countries = "GQ"
	CountriesER Countries = "ER"
	CountriesEE Countries = "EE"
	CountriesSZ Countries = "SZ"
	CountriesET Countries = "ET"
	CountriesFK Countries = "FK"
	CountriesFO Countries = "FO"
	CountriesFJ Countries = "FJ"
	CountriesFI Countries = "FI"
	CountriesFR Countries = "FR"
	CountriesGF Countries = "GF"
	CountriesPF Countries = "PF"
	CountriesTF Countries = "TF"
	CountriesGA Countries = "GA"
	CountriesGM Countries = "GM"
	CountriesGE Countries = "GE"
	CountriesDE Countries = "DE"
	CountriesGH Countries = "GH"
	CountriesGI Countries = "GI"
	CountriesGR Countries = "GR"
	CountriesGL Countries = "GL"
	CountriesGD Countries = "GD"
	CountriesGP Countries = "GP"
	CountriesGU Countries = "GU"
	CountriesGT Countries = "GT"
	CountriesGG Countries = "GG"
	CountriesGN Countries = "GN"
	CountriesGW Countries = "GW"
	CountriesGY Countries = "GY"
	CountriesHT Countries = "HT"
	CountriesHM Countries = "HM"
	CountriesVA Countries = "VA"
	CountriesHN Countries = "HN"
	CountriesHK Countries = "HK"
	CountriesHU Countries = "HU"
	CountriesIS Countries = "IS"
	CountriesIN Countries = "IN"
	CountriesID Countries = "ID"
	CountriesIR Countries = "IR"
	CountriesIQ Countries = "IQ"
	CountriesIE Countries = "IE"
	CountriesIM Countries = "IM"
	CountriesIL Countries = "IL"
	CountriesIT Countries = "IT"
	CountriesJM Countries = "JM"
	CountriesJP Countries = "JP"
	CountriesJE Countries = "JE"
	CountriesJO Countries = "JO"
	CountriesKZ Countries = "KZ"
	CountriesKE Countries = "KE"
	CountriesKI Countries = "KI"
	CountriesKP Countries = "KP"
	CountriesKR Countries = "KR"
	CountriesKW Countries = "KW"
	CountriesKG Countries = "KG"
	CountriesLA Countries = "LA"
	CountriesLV Countries = "LV"
	CountriesLB Countries = "LB"
	CountriesLS Countries = "LS"
	CountriesLR Countries = "LR"
	CountriesLY Countries = "LY"
	CountriesLI Countries = "LI"
	CountriesLT Countries = "LT"
	CountriesLU Countries = "LU"
	CountriesMO Countries = "MO"
	CountriesMK Countries = "MK"
	CountriesMG Countries = "MG"
	CountriesMW Countries = "MW"
	CountriesMY Countries = "MY"
	CountriesMV Countries = "MV"
	CountriesML Countries = "ML"
	CountriesMT Countries = "MT"
	CountriesMH Countries = "MH"
	CountriesMQ Countries = "MQ"
	CountriesMR Countries = "MR"
	CountriesMU Countries = "MU"
	CountriesYT Countries = "YT"
	CountriesMX Countries = "MX"
	CountriesFM Countries = "FM"
	CountriesMD Countries = "MD"
	CountriesMC Countries = "MC"
	CountriesMN Countries = "MN"
	CountriesME Countries = "ME"
	CountriesMS Countries = "MS"
	CountriesMA Countries = "MA"
	CountriesMZ Countries = "MZ"
	CountriesMM Countries = "MM"
	CountriesNA Countries = "NA"
	CountriesNR Countries = "NR"
	CountriesNP Countries = "NP"
	CountriesNL Countries = "NL"
	CountriesNC Countries = "NC"
	CountriesNZ Countries = "NZ"
	CountriesNI Countries = "NI"
	CountriesNE Countries = "NE"
	CountriesNG Countries = "NG"
	CountriesNU Countries = "NU"
	CountriesNF Countries = "NF"
	CountriesMP Countries = "MP"
	CountriesNO Countries = "NO"
	CountriesOM Countries = "OM"
	CountriesPK Countries = "PK"
	CountriesPW Countries = "PW"
	CountriesPS Countries = "PS"
	CountriesPA Countries = "PA"
	CountriesPG Countries = "PG"
	CountriesPY Countries = "PY"
	CountriesPE Countries = "PE"
	CountriesPH Countries = "PH"
	CountriesPN Countries = "PN"
	CountriesPL Countries = "PL"
	CountriesPT Countries = "PT"
	CountriesPR Countries = "PR"
	CountriesQA Countries = "QA"
	CountriesRE Countries = "RE"
	CountriesRO Countries = "RO"
	CountriesRU Countries = "RU"
	CountriesRW Countries = "RW"
	CountriesBL Countries = "BL"
	CountriesSH Countries = "SH"
	CountriesKN Countries = "KN"
	CountriesLC Countries = "LC"
	CountriesMF Countries = "MF"
	CountriesPM Countries = "PM"
	CountriesVC Countries = "VC"
	CountriesWS Countries = "WS"
	CountriesSM Countries = "SM"
	CountriesST Countries = "ST"
	CountriesSA Countries = "SA"
	CountriesSN Countries = "SN"
	CountriesRS Countries = "RS"
	CountriesSC Countries = "SC"
	CountriesSL Countries = "SL"
	CountriesSG Countries = "SG"
	CountriesSX Countries = "SX"
	CountriesSK Countries = "SK"
	CountriesSI Countries = "SI"
	CountriesSB Countries = "SB"
	CountriesSO Countries = "SO"
	CountriesZA Countries = "ZA"
	CountriesGS Countries = "GS"
	CountriesSS Countries = "SS"
	CountriesES Countries = "ES"
	CountriesLK Countries = "LK"
	CountriesSD Countries = "SD"
	CountriesSR Countries = "SR"
	CountriesSJ Countries = "SJ"
	CountriesSE Countries = "SE"
	CountriesCH Countries = "CH"
	CountriesSY Countries = "SY"
	CountriesTW Countries = "TW"
	CountriesTJ Countries = "TJ"
	CountriesTZ Countries = "TZ"
	CountriesTH Countries = "TH"
	CountriesTL Countries = "TL"
	CountriesTG Countries = "TG"
	CountriesTK Countries = "TK"
	CountriesTO Countries = "TO"
	CountriesTT Countries = "TT"
	CountriesTN Countries = "TN"
	CountriesTR Countries = "TR"
	CountriesTM Countries = "TM"
	CountriesTC Countries = "TC"
	CountriesTV Countries = "TV"
	CountriesUG Countries = "UG"
	CountriesUA Countries = "UA"
	CountriesAE Countries = "AE"
	CountriesGB Countries = "GB"
	CountriesUM Countries = "UM"
	CountriesUS Countries = "US"
	CountriesUY Countries = "UY"
	CountriesUZ Countries = "UZ"
	CountriesVU Countries = "VU"
	CountriesVE Countries = "VE"
	CountriesVN Countries = "VN"
	CountriesVG Countries = "VG"
	CountriesVI Countries = "VI"
	CountriesWF Countries = "WF"
	CountriesEH Countries = "EH"
	CountriesYE Countries = "YE"
	CountriesZM Countries = "ZM"
	CountriesZW Countries = "ZW"
)

func (e *Countries) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Countries(s)
	case string:
		*e = Countries(s)
	default:
		return fmt.Errorf("unsupported scan type for Countries: %T", src)
	}
	return nil
}

type NullCountries struct {
	Countries Countries
	Valid     bool // Valid is true if Countries is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCountries) Scan(value interface{}) error {
	if value == nil {
		ns.Countries, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Countries.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCountries) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Countries), nil
}

type Currency string

const (
	CurrencyAED Currency = "AED"
	CurrencyAFN Currency = "AFN"
	CurrencyALL Currency = "ALL"
	CurrencyAMD Currency = "AMD"
	CurrencyAOA Currency = "AOA"
	CurrencyARS Currency = "ARS"
	CurrencyAUD Currency = "AUD"
	CurrencyAWG Currency = "AWG"
	CurrencyAZN Currency = "AZN"
	CurrencyBAM Currency = "BAM"
	CurrencyBBD Currency = "BBD"
	CurrencyBDT Currency = "BDT"
	CurrencyBGN Currency = "BGN"
	CurrencyBHD Currency = "BHD"
	CurrencyBIF Currency = "BIF"
	CurrencyBMD Currency = "BMD"
	CurrencyBND Currency = "BND"
	CurrencyBOB Currency = "BOB"
	CurrencyBOV Currency = "BOV"
	CurrencyBRL Currency = "BRL"
	CurrencyBSD Currency = "BSD"
	CurrencyBTN Currency = "BTN"
	CurrencyBWP Currency = "BWP"
	CurrencyBYN Currency = "BYN"
	CurrencyBZD Currency = "BZD"
	CurrencyCAD Currency = "CAD"
	CurrencyCDF Currency = "CDF"
	CurrencyCHE Currency = "CHE"
	CurrencyCHF Currency = "CHF"
	CurrencyCHW Currency = "CHW"
	CurrencyCLF Currency = "CLF"
	CurrencyCLP Currency = "CLP"
	CurrencyCNY Currency = "CNY"
	CurrencyCOP Currency = "COP"
	CurrencyCOU Currency = "COU"
	CurrencyCRC Currency = "CRC"
	CurrencyCUP Currency = "CUP"
	CurrencyCVE Currency = "CVE"
	CurrencyCZK Currency = "CZK"
	CurrencyDJF Currency = "DJF"
	CurrencyDKK Currency = "DKK"
	CurrencyDOP Currency = "DOP"
	CurrencyDZD Currency = "DZD"
	CurrencyEGP Currency = "EGP"
	CurrencyERN Currency = "ERN"
	CurrencyETB Currency = "ETB"
	CurrencyEUR Currency = "EUR"
	CurrencyFJD Currency = "FJD"
	CurrencyFKP Currency = "FKP"
	CurrencyGBP Currency = "GBP"
	CurrencyGEL Currency = "GEL"
	CurrencyGHS Currency = "GHS"
	CurrencyGIP Currency = "GIP"
	CurrencyGMD Currency = "GMD"
	CurrencyGNF Currency = "GNF"
	CurrencyGTQ Currency = "GTQ"
	CurrencyGYD Currency = "GYD"
	CurrencyHKD Currency = "HKD"
	CurrencyHNL Currency = "HNL"
	CurrencyHTG Currency = "HTG"
	CurrencyHUF Currency = "HUF"
	CurrencyIDR Currency = "IDR"
	CurrencyILS Currency = "ILS"
	CurrencyINR Currency = "INR"
	CurrencyIQD Currency = "IQD"
	CurrencyIRR Currency = "IRR"
	CurrencyISK Currency = "ISK"
	CurrencyJMD Currency = "JMD"
	CurrencyJOD Currency = "JOD"
	CurrencyJPY Currency = "JPY"
	CurrencyKES Currency = "KES"
	CurrencyKGS Currency = "KGS"
	CurrencyKHR Currency = "KHR"
	CurrencyKMF Currency = "KMF"
	CurrencyKPW Currency = "KPW"
	CurrencyKRW Currency = "KRW"
	CurrencyKWD Currency = "KWD"
	CurrencyKYD Currency = "KYD"
	CurrencyKZT Currency = "KZT"
	CurrencyLAK Currency = "LAK"
	CurrencyLBP Currency = "LBP"
	CurrencyLKR Currency = "LKR"
	CurrencyLRD Currency = "LRD"
	CurrencyLSL Currency = "LSL"
	CurrencyLYD Currency = "LYD"
	CurrencyMAD Currency = "MAD"
	CurrencyMDL Currency = "MDL"
	CurrencyMGA Currency = "MGA"
	CurrencyMKD Currency = "MKD"
	CurrencyMMK Currency = "MMK"
	CurrencyMNT Currency = "MNT"
	CurrencyMOP Currency = "MOP"
	CurrencyMRU Currency = "MRU"
	CurrencyMUR Currency = "MUR"
	CurrencyMVR Currency = "MVR"
	CurrencyMWK Currency = "MWK"
	CurrencyMXN Currency = "MXN"
	CurrencyMXV Currency = "MXV"
	CurrencyMYR Currency = "MYR"
	CurrencyMZN Currency = "MZN"
	CurrencyNAD Currency = "NAD"
	CurrencyNGN Currency = "NGN"
	CurrencyNIO Currency = "NIO"
	CurrencyNOK Currency = "NOK"
	CurrencyNPR Currency = "NPR"
	CurrencyNZD Currency = "NZD"
	CurrencyOMR Currency = "OMR"
	CurrencyPAB Currency = "PAB"
	CurrencyPEN Currency = "PEN"
	CurrencyPGK Currency = "PGK"
	CurrencyPHP Currency = "PHP"
	CurrencyPKR Currency = "PKR"
	CurrencyPLN Currency = "PLN"
	CurrencyPYG Currency = "PYG"
	CurrencyQAR Currency = "QAR"
	CurrencyRON Currency = "RON"
	CurrencyRSD Currency = "RSD"
	CurrencyRUB Currency = "RUB"
	CurrencyRWF Currency = "RWF"
	CurrencySAR Currency = "SAR"
	CurrencySBD Currency = "SBD"
	CurrencySCR Currency = "SCR"
	CurrencySDG Currency = "SDG"
	CurrencySEK Currency = "SEK"
	CurrencySGD Currency = "SGD"
	CurrencySHP Currency = "SHP"
	CurrencySLE Currency = "SLE"
	CurrencySOS Currency = "SOS"
	CurrencySRD Currency = "SRD"
	CurrencySSP Currency = "SSP"
	CurrencySTN Currency = "STN"
	CurrencySVC Currency = "SVC"
	CurrencySYP Currency = "SYP"
	CurrencySZL Currency = "SZL"
	CurrencyTHB Currency = "THB"
	CurrencyTJS Currency = "TJS"
	CurrencyTMT Currency = "TMT"
	CurrencyTND Currency = "TND"
	CurrencyTOP Currency = "TOP"
	CurrencyTRY Currency = "TRY"
	CurrencyTTD Currency = "TTD"
	CurrencyTWD Currency = "TWD"
	CurrencyTZS Currency = "TZS"
	CurrencyUAH Currency = "UAH"
	CurrencyUGX Currency = "UGX"
	CurrencyUSD Currency = "USD"
	CurrencyUSN Currency = "USN"
	CurrencyUYI Currency = "UYI"
	CurrencyUYU Currency = "UYU"
	CurrencyUYW Currency = "UYW"
	CurrencyUZS Currency = "UZS"
	CurrencyVED Currency = "VED"
	CurrencyVES Currency = "VES"
	CurrencyVND Currency = "VND"
	CurrencyVUV Currency = "VUV"
	CurrencyWST Currency = "WST"
	CurrencyXAD Currency = "XAD"
	CurrencyXAF Currency = "XAF"
	CurrencyXAG Currency = "XAG"
	CurrencyXAU Currency = "XAU"
	CurrencyXBA Currency = "XBA"
	CurrencyXBB Currency = "XBB"
	CurrencyXBC Currency = "XBC"
	CurrencyXBD Currency = "XBD"
	CurrencyXCD Currency = "XCD"
	CurrencyXCG Currency = "XCG"
	CurrencyXDR Currency = "XDR"
	CurrencyXOF Currency = "XOF"
	CurrencyXPD Currency = "XPD"
	CurrencyXPF Currency = "XPF"
	CurrencyXPT Currency = "XPT"
	CurrencyXSU Currency = "XSU"
	CurrencyXTS Currency = "XTS"
	CurrencyXUA Currency = "XUA"
	CurrencyXXX Currency = "XXX"
	CurrencyYER Currency = "YER"
	CurrencyZAR Currency = "ZAR"
	CurrencyZMW Currency = "ZMW"
	CurrencyZWG Currency = "ZWG"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type ItemType string

const (
	ItemTypePRODUCT ItemType = "PRODUCT"
	ItemTypeASSET   ItemType = "ASSET"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type Account struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Countries
	Deleted   bool
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

type AccountsUsers struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Group struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Name        string
	ParentID    uuid.NullUUID
	AccountID   uuid.UUID
}

type Inventory struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type Item struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Description sql.NullString
	Name        string
	Type        ItemType
	AccountID   uuid.UUID
	GroupID     uuid.NullUUID
}

type ItemIdentifier struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type Price struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  Currency
	Amount    int32
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Name           sql.NullString
}
