// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPrice = `-- name: CreatePrice :one
INSERT INTO prices
(
    id,
    created_at,
    updated_at,
    currency,
    amount,
    account_id,
    item_id
)
VALUES
(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    created_at,
    updated_at,
    currency,
    amount,
    item_id AS item
`

type CreatePriceParams struct {
	Currency  Currency
	Amount    int32
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type CreatePriceRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  Currency
	Amount    int32
	Item      uuid.UUID
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) (CreatePriceRow, error) {
	row := q.db.QueryRowContext(ctx, createPrice,
		arg.Currency,
		arg.Amount,
		arg.AccountID,
		arg.ItemID,
	)
	var i CreatePriceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Amount,
		&i.Item,
	)
	return i, err
}

const deletePrice = `-- name: DeletePrice :exec

DELETE FROM prices
WHERE id = $1 AND account_id = $2
`

type DeletePriceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeletePrice(ctx context.Context, arg DeletePriceParams) error {
	_, err := q.db.ExecContext(ctx, deletePrice, arg.ID, arg.AccountID)
	return err
}

const getPrice = `-- name: GetPrice :one

SELECT
    id,
    created_at,
    updated_at,
    currency,
    amount,
    item_id AS item
FROM prices
WHERE id = $1 AND account_id = $2
`

type GetPriceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetPriceRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  Currency
	Amount    int32
	Item      uuid.UUID
}

func (q *Queries) GetPrice(ctx context.Context, arg GetPriceParams) (GetPriceRow, error) {
	row := q.db.QueryRowContext(ctx, getPrice, arg.ID, arg.AccountID)
	var i GetPriceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Amount,
		&i.Item,
	)
	return i, err
}

const listPrices = `-- name: ListPrices :many

SELECT
    id,
    created_at,
    updated_at,
    currency,
    amount,
    item_id AS item
FROM prices
WHERE account_id = $1
AND
    (
        $2::timestamp IS NULL 
        OR $2::timestamp > created_at
    )
AND 
    (
        $3::timestamp IS NULL 
        OR $3::timestamp < created_at
    )
AND 
    (
        $4::timestamp IS NULL 
        OR $4::timestamp >= created_at
    )
AND 
    (
        $5::timestamp IS NULL 
        OR $5::timestamp <= created_at
    )
AND 
    (
        $6::timestamp IS NULL 
        OR $6::timestamp > updated_at
    )
AND 
    (
        $7::timestamp IS NULL 
        OR $7::timestamp < updated_at
    )
AND 
    (
        $8::timestamp IS NULL 
        OR $8::timestamp >= updated_at
    )
AND 
    (
        $9::timestamp IS NULL 
        OR $9::timestamp <= updated_at
    )
AND 
    (
        $10::uuid IS NULL
        OR $10::uuid > id
    )
AND 
    (
        $11::uuid IS NULL
        OR $11::uuid < id
    )
ORDER BY created_at DESC
LIMIT COALESCE($12::int, 10)
`

type ListPricesParams struct {
	AccountID     uuid.UUID
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtLt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	Limit         sql.NullInt32
}

type ListPricesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  Currency
	Amount    int32
	Item      uuid.UUID
}

func (q *Queries) ListPrices(ctx context.Context, arg ListPricesParams) ([]ListPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrices,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricesRow
	for rows.Next() {
		var i ListPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Currency,
			&i.Amount,
			&i.Item,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrice = `-- name: UpdatePrice :one

UPDATE prices
SET
    updated_at = NOW(),
    currency = COALESCE($1, currency),
    amount = COALESCE($2, amount)
WHERE id = $3 AND account_id = $4
RETURNING
    id,
    created_at,
    updated_at,
    currency,
    amount,
    item_id AS item
`

type UpdatePriceParams struct {
	Currency  NullCurrency
	Amount    sql.NullInt32
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdatePriceRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Currency  Currency
	Amount    int32
	Item      uuid.UUID
}

func (q *Queries) UpdatePrice(ctx context.Context, arg UpdatePriceParams) (UpdatePriceRow, error) {
	row := q.db.QueryRowContext(ctx, updatePrice,
		arg.Currency,
		arg.Amount,
		arg.ID,
		arg.AccountID,
	)
	var i UpdatePriceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.Amount,
		&i.Item,
	)
	return i, err
}
